### ISSUE TITLE
Unclear "required" field in TCT template

### ISSUE THREAD

**Issue by erik-edling** [eiffel-community/eiffel-remrem-semantics#101]
### Description

In the template for TCT The field recipeId does not say that it's required, although it is. The template should be updated so that it is clear. 
### Motivation

It's hard to create an event from the template since the field is required but not stated that it is.

**Comment by e-pettersson-ericsson** [comment]
I agree, I also ran in to this issue when generating the TestCaseTtriggered event form the template and left the empty string in "recipeId". The template should reflect the [protocol documentation](https://github.com/eiffel-community/eiffel/blob/master/eiffel-vocabulary/EiffelTestCaseTriggeredEvent.md#datarecipeid) about this.
