### ISSUE TITLE
Move the documentation from gh-pages to master.

### ISSUE THREAD

**Issue by SantoshNC68** [eiffel-community/eiffel-remrem-semantics#115]
### Description
Move the documentation from gh-pages to master branch to enable better readability.

### Motivation
To enable common documentation across eiffel community.

**Comment by e-pettersson-ericsson** [comment]
I like this proposal. Could it also be considered to convert the documentation to markdown? That way it's easier to maintain 😄

**Comment by SantoshNC68** [comment]
Yes today we have the mark down created, so it will be markdown pages only.

**Comment by e-pettersson-ericsson** [comment]
> Yes today we have the mark down created, so it will be markdown pages only.

Great! These two issues in remrem-generate and remrem-publish are also related and should maybe be treated the same? I.e. move from gh-pages to master branch? 
* https://github.com/eiffel-community/eiffel-remrem-generate/issues/137
* https://github.com/eiffel-community/eiffel-remrem-publish/issues/168

**Comment by xlakann** [comment]
Documentation changes got approvals and merged with the pull request 
https://github.com/eiffel-community/eiffel-remrem-semantics/pull/122
and released with jitpack version 2.0.9.
