### ISSUE TITLE
Eiffel event generation overrides valid meta.id and time

### ISSUE THREAD

**Issue by strangeweaver** [eiffel-community/eiffel-remrem-semantics#116]
### Description
The Event.generateMeta() method should not overwrite meta.id or meta.time if valid values already exist in the meta object passed in.
https://github.com/eiffel-community/eiffel-remrem-semantics/blob/master/src/main/java/com/ericsson/eiffel/semantics/events/Event.java#L41

### Motivation
When generating an Event it is the event emitter may want to specify a specific uuid (e.g. reproducible uuid) to identify the Event. To support this presently, the event emitter needs to call the remrem-generate, parse the response and replace the id in that response. This processing overhead would be unnecessary if the the Event.generateMeta did not overwrite the id passed in.

### Exemplification
reproducible uuids can be used to avoid lookups when creating Events with links. For example a ScS could have a uuid that used the VCS commit identifier as a seed. It then becomes a relatively simple task to create an Act event linked to the ScS

### Benefits
Reduction in processing overhead on client
Logically consistent with remrem-generate for other fields Eiffel message

**Comment by SantoshNC68** [comment]
Hi @strangeweaver , the possibility to allow users to provide meta.id and meta.time will cause problems when we are talking in terms of immutability. We can end up having creating a Id that is already existing which we would not want to be in. Hence I don't think this as a good way.

**Comment by SantoshNC68** [comment]
@strangeweaver Can I close this issue.

**Comment by SantoshNC68** [comment]
Closing this issue due to lack of discussion.
