### ISSUE TITLE
MsgServer.generateMsg doesn't validate input

### ISSUE THREAD

**Issue by magnusbaeck** [eiffel-community/eiffel-remrem-semantics#117]
### Description
MsgServer.generateMsg() blindly assumes that various keys are available in the input JSON object. If one of the required keys is missing a NullPointerException will be thrown. You'll have to inspect the stack trace (if available) and correlate it to the source code to figure out what the problem was. This is true for msgParams, msgParams,meta, and eventParams.

When adding these checks I think it's reasonable to consider which keys should really be required. For example, this is smallest input document that will pass muster:
```javascript
{
  "msgParams": {
    "meta": {}
  },
  "eventParams": {
    "data": {}
  }
}
```
Should we really require msgParams or msgParams.meta? The value of requiring a value but accepting an empty object is unclear to me.

### Motivation
Giving callers reasonably detailed feedback when the input data is bad is arguably a good idea, and generateMsg() already does in some cases (a bad msgType parameter) so if nothing else it'd be nice with some consistency. This is particularly true when the bad value isn't the method parameter itself but a value accessed from the parameter; getting an NPE when you pass a null parameter is more acceptable.

### Exemplification
I discovered this when I was playing around with REMReM Generate and trying to pass an empty JSON body. This resulted in a 500 error with nothing in the REMReM logs (which is a separate issue; see https://github.com/eiffel-community/eiffel-remrem-generate/issues/140) and I had to hack in extra logging to get the stack trace and look in the source code to figure out what the problem was.

**Comment by xumakap** [comment]
yes we noticed that, 500 Internal error is not the exact status code for empty json or NPE. Will try to address it in a fix and you can check the changes.

**Comment by SantoshNC68** [comment]
Perhaps this has to be moved to REMReM Generate... there is a PR: https://github.com/eiffel-community/eiffel-remrem-generate/pull/154/ related to this.

**Comment by zkxxdiv** [comment]
Added changes in Semantics PR: https://github.com/eiffel-community/eiffel-remrem-semantics/issues/117
