### ISSUE TITLE
Schema update process removes copyright header from files

### ISSUE THREAD

**Issue by magnusbaeck** [eiffel-community/eiffel-remrem-semantics#133]
### Description
Running `mvn clean install -P generate-events` to generate new POJO classes will remove the copyright header in all files. Given the number of affected files it's very annoying to have to skip through those changes. We should either we rid of the copyright header or make sure the file generation prepends the generated files with the desired header.

### Motivation
Updating this repository as the protocol changes shouldn't be hard or require additional manual steps that can be automated.

### Exemplification
N/A

### Benefits
Easier to update schemas, decreased risk of mistakes.

### Possible Drawbacks
None.

**Comment by Vaishnavi-Enugala** [comment]
After schema update process , added copyright header to generated POJO classes using https://mvnrepository.com/artifact/com.mycila.maven-license-plugin/maven-license-plugin and changes are merged hence closing this issue.

**Comment by magnusbaeck** [comment]
@Vaishnavi-Enugala, you said you'd close the issue but it's still open. As far as I can tell all changes are in place, so... close?

**Comment by RajuBeemreddy1** [comment]
All changes are now in place for this issue. Closing this issue.
