### ISSUE TITLE
Update to Orizaba edition of protocol

### ISSUE THREAD

**Issue by magnusbaeck** [eiffel-community/eiffel-remrem-semantics#141]
### Description
The [Orizaba edition of the Eiffel protocol](https://github.com/eiffel-community/eiffel/releases/tag/edition-orizaba) has been released and REMReM should be updated to that edition. All events have been updated in that edition.

### Motivation
The Orizaba edition includes a few interesting changes that we'd like to be able to use with REMReM.

### Exemplification
N/A

### Benefits
REMReM clients get access to the latest event versions.

### Possible Drawbacks
None. The changes in Orizaba are backwards compatible.

**Comment by m-linner-ericsson** [comment]
Update this when we have released the Arica edition

**Comment by magnusbaeck** [comment]
There, now the issue references Arica instead of Lyon.

**Comment by m-linner-ericsson** [comment]
Now the issue references Orizaba instead of Arica
