### ISSUE TITLE
Need more information from Event class as this doesn't have information about data and links

### ISSUE THREAD

**Issue by SantoshNC68** [eiffel-community/eiffel-remrem-semantics#79]
Need data and Links information in the **Event** class that can be used to fetch information about the events.

**Comment by rogpers-ericsson** [comment]
This would make sense. 
What would the returned types be though?

- The links would, looking at the code, return a List<Link> which would be generic enough I guess.
- However, what should data return?

**Comment by guwenqing** [comment]
I think we are asking a common-sense thing, data should return the abstract form so we can at least access properties that are common to all.
I will contact OPO to escalate it.

**Comment by evasiba-ericsson** [comment]
In my opinion returning a Json object from the event and access the information with the path as a key is more general applicable to all Json based messages.

**Comment by evasiba-ericsson** [comment]
Sure. Lets see who has time to contribute with this.

**Comment by xmairaa** [comment]
### The below properties are suitable properties to access from Event Class.

**Meta:**
- id
- type
- version
- time
- tags
- source
- security

**Data:**
- customData
In data, properties are different for each Event

**Links:**
- all links (Type, Target)

Created a pull request Please have a look.
https://github.com/Ericsson/eiffel-remrem-semantics/pull/92

**Comment by SantoshNC68** [comment]
Closing the issue as there are no more inputs on this.
